const constants = {
  BACKEND_URL: 'https://youtifybackend.azurewebsites.net',
  BACKEND_URL_DEV: 'http://localhost:3001',
  ACTIONS: {
    FETCH_VIDEOS: 'FETCH_VIDEOS',
    SELECT_VIDEO: 'SELECT_VIDEO',
    REMOVE_SELECTED_VIDEO: 'REMOVE_SELECTED_VIDEO',
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    FETCH_PLAYLISTS: 'FETCH_PLAYLISTS',
    CREATE_PLAYLIST: 'CREATE_PLAYLIST',
    REMOVE_PLAYLIST: 'REMOVE_PLAYLIST',
    ADD_VIDEO_TO_PLAYLIST: 'ADD_VIDEO_TO_PLAYLIST',
    REMOVE_VIDEO_FROM_PLAYLIST: 'REMOVE_VIDEO_FROM_PLAYLIST',
    CLEAN_PLAYLISTS: 'CLEAN_PLAYLISTS',
    ADDING_PLAYLIST: 'ADDING_PLAYLIST'
  }
};

export default constants;